name: isaac-steam-workshop-upload
description: "Upload a Binding of Isaac: Repentance mod to the Steam Workshop"

branding:
  icon: arrow-up
  color: gray-dark

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.mod_path }}
    - ${{ inputs.ignore_files }}
    - ${{ inputs.change_note }}
    - ${{ inputs.commit_message }}

inputs:
  mod_path:
    description: "The path to the subdirectory of the repository that should be uploaded to the Steam Workshop."
    required: true
  ignore_files:
    description: "A comma separated list of the files to ignore, if any."
    required: false
    default: ""
  change_note:
    description: "The description of"
    required: false
    default: "Version: {VERSION}"
  commit_message:
    description: "The commit that triggered this action. (This is automatically set and does not have to be specified.)"
    required: false
    default: ${{ github.event.head_commit.message }}
