name: isaac-steam-workshop-upload
description: "Upload a Binding of Isaac: Repentance mod to the Steam Workshop"

branding:
  icon: arrow-up
  color: gray-dark

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.mod_path }}
    - ${{ inputs.commit_message }}

inputs:
  mod_path:
    description: "The path to the subdirectory of the repository that should be uploaded to the Steam Workshop."
    required: true
  commit_message:
    description: "Automatically set to the commit message corresponding to the commit that triggered this action."
    required: false
    default: ${{ github.event.head_commit.message }}
