name: isaac-steam-workshop-upload
description: "Upload a Binding of Isaac: Repentance mod to the Steam Workshop"

branding:
  icon: arrow-up
  color: gray-dark

runs:
  using: docker
  image: Dockerfile
