name: isaac-steam-workshop-upload
description: "Upload a Binding of Isaac: Repentance mod to the Steam Workshop"

branding:
  icon: arrow-up
  color: gray-dark

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.mod_path }}

inputs:
  mod_path:
    description: "The path to the subdirectory of the repository that should be uploaded to the Steam Workshop."
    required: true
